### ISSUE TITLE
Example App: Unknown execution context

### ISSUE THREAD

**Issue by eduardomoroni** [esbenp/react-native-clean-form#11]
I'm trying to run example App and I'm getting this:
<img width="381" alt="screen shot 2017-03-20 at 08 36 56" src="https://cloud.githubusercontent.com/assets/823150/24098272/6f0e48ba-0d48-11e7-86da-d995fcae4347.png">

**Comment by markusguenther** [comment]
Maybe it is fixed now ... try again the the current master.

**Comment by markusguenther** [comment]
Is this still relevant? If yes please provide more information for reproduction of this issue.

**Comment by eduardomoroni** [comment]
I followed these steps: https://github.com/esbenp/react-native-clean-form#run-the-example
I tried again today and got the same error. Maybe something wrong with my environment

**Comment by markusguenther** [comment]
@eduardomoroni I tried the steps and everything works fine ... 

Do you have problems with a new react-native app or other apps?
It is not so easy to say what can be wrong in the environment.

Can you try: 

```bash
react-native init foo && cd foo
react-native run-ios
```

And please check the versions: 

```
node --version && npm --version && yarn --version && react-native --version
v5.2.0
4.0.5
0.21.3
react-native-cli: 2.0.0
react-native: n/a - not inside a React Native project directory
```

I also use actually iOS 10.3

**Comment by esbenp** [comment]
Also add your OS and version :-)

**Comment by eduardomoroni** [comment]
```
Node v6.10.1
Npm 3.10.10
Yarn 0.18.1
react-native-cli: 2.0.1
react-native: 0.40.0
Mac OS Sierra 10.12.3
```

I think we should close this issue guys, `react-native-clean-form` is working well on my app. I just can't run example app.
Thanks Everyone!

**Comment by markusguenther** [comment]
Ok but it is strange :/ ...

**Comment by markusguenther** [comment]
Thanks for reporting ... maybe I try it again on my second Mac.
