### ISSUE TITLE
please push 0.3.0 to npm registry, it's still at 0.1.0

### ISSUE THREAD

**Issue by clindsey** [esbenp/react-native-clean-form#39]
seems like a lot of the `duplicate module name` errors can be solved by using the latest version of this project instead of the default installed by npm.

**Problem**: Using `npm install react-native-clean-form` installs version 0.1.0

**Workaround**: Manually using `"react-native-clean-form": "esbenp/react-native-clean-form",` in package.json will cause version 0.3.0 to be installed.

#8, #27, #37

**Comment by markusguenther** [comment]
Your right ;) ... but only @esbenp has access to the npm package. I can merge here but nothing more.

**Comment by esbenp** [comment]
`0.4.1` has been created and published :-)

**Comment by lionhive** [comment]
Thank you!
