### ISSUE TITLE
Not working with Expo Or create-react-native-app

### ISSUE THREAD

**Issue by giautm** [esbenp/react-native-clean-form#41]
This package currently can't work with Expo. Because it used `react-native-vector-icons`.
Can be change to `@expo/vector-icon` to make very body be happy? 👍

**Comment by sabativi** [comment]
@expo/vector-icon has the same api as react-native-vector-icons

https://docs.expo.io/versions/v17.0.0/guides/icons.html

> expo/vector-icons is built on top of react-native-vector-icons and uses a similar API. The only difference is @expo/vector-icons uses a more idiomatic import style:
> 
> import { Ionicons } from '@expo/vector-icons'; instead of.. import Ionicons from 'react-native-vector-icons/Ionicons';.

**Comment by giautm** [comment]
@sabativi : So, is that PR unnecessary?
