### ISSUE TITLE
react-native Failed to parse declaration padding 12 8

### ISSUE THREAD

**Issue by erdalceylan** [esbenp/react-native-clean-form#50]
solution: 

Theme.js line 22
change padding : '12 8'
    paddingTop: 10,
    paddingRight: 8,
    paddingBottom:10,
    paddingLeft: 8,

Theme.js line 32
change padding: '10 0' to 
    paddingTop: 0,
    paddingRight: 10,
    paddingBottom: 0,
    paddingLeft: 10,

Fieldset.js line 19
const FieldsetWrapper = styled.View`
  borderBottomColor: ${props => props.theme.Fieldset.borderBottomColor };
  borderBottomWidth: ${props => props.last ? 0 : props.theme.Fieldset.borderBottomWidth };
  paddingTop : ${props => props.theme.Fieldset.paddingTop };
  paddingRight : ${props => props.theme.Fieldset.paddingRight };
  paddingBottom : ${props => props.theme.Fieldset.paddingBottom };
  paddingLeft : ${props => props.theme.Fieldset.paddingLeft };
`
FormGroup.js line 28
const FormGroupWrapper = styled.View`
  align-items: ${props => props.inlineLabel ? 'center' : 'stretch' };
  border-color: ${props => props.error ? props.theme.FormGroup.errorBorderColor : props.theme.FormGroup.borderColor};
  border-radius: ${props => props.theme.FormGroup.borderRadius};
  border-style: ${props => props.theme.FormGroup.borderStyle};
  border-width: ${props => props.border ? props.theme.FormGroup.borderWidth : 0};
  flex-direction: ${props => props.inlineLabel ? 'row' : 'column' };
  justify-content: flex-start;
  height: ${props => calculateHeight(props)};
  marginBottom: ${props => props.theme.FormGroup.marginBottom};
  paddingTop : ${props => props.theme.FormGroup.paddingTop };
  paddingRight : ${props => props.theme.FormGroup.paddingRight };
  paddingBottom : ${props => props.theme.FormGroup.paddingBottom };
  paddingLeft : ${props => props.theme.FormGroup.paddingLeft };
`

**Comment by williams-voon** [comment]
You can also change package.json, 

- "styled-components": ">=1.4"
+"styled-components": "^1.4"

It is my solution.

**Comment by xiongxiong** [comment]
Waiting for publishing a new version ...

**Comment by esbenp** [comment]
#53
