### ISSUE TITLE
Naming collision for react-native-vector-icons

### ISSUE THREAD

**Issue by BookSock** [esbenp/react-native-clean-form#6]
react-native run-ios doesn't work anymore on my project with the error paraphrased below:

@providesModule declaration with same name across two different files
duplicate module name: react-native-vector-icons

The two paths are the package.json inside of the node module "react-native" and the the same package.json inside of the node module "react-native-clean-form" inside of the node module "react-native" that is nested inside of "react-native-clean-form"

I solved it by deleting the "react-native" node module that is nested inside of the "react-native-clean-form" node module, but I'm not sure what the proper fix is. Maybe removing react-native from the dependencies list of react-native-clean-form? 

Also since I don't think there was any change in this repo recently, did another dependency change that made this break?

Also - I did do "react-native link" command and also tried reinstalling without linking and both ways produced the same error

**Comment by tonyxiao** [comment]
Experiencing the same issue. It basically makes `react-native-clean-form` not usable as is.

**Comment by wilomgfx** [comment]
@esbenp +1

**Comment by markusguenther** [comment]
I created a pull request ... this fixes the hassle for me. 

https://github.com/esbenp/react-native-clean-form/pull/12

**Comment by markusguenther** [comment]
@esbenp this can be closed after #12 has been merged ;)
