### ISSUE TITLE
fatal SyntaxError in index.js of redux-form sub module

### ISSUE THREAD

**Issue by SamMatthewsIsACommonName** [esbenp/react-native-clean-form#7]
Hi, on trying to import anything from the redux-form subdirectory of this libary I'm getting the following error:

<img width="361" alt="screen shot 2017-02-15 at 10 15 44" src="https://cloud.githubusercontent.com/assets/21329063/22949728/19fe9090-f368-11e6-9f42-66290620a117.png">

I'm using react native 40.0.0

The error referred to is the bottom line here:

````
import createInputs from './createInputs'
import createInputCreator from './createInputCreator'
import { Field } from 'redux-form'

export {
  Input,
  Select,
  Switch
} from createInputs(createInputCreator(Field))
````
Is this something I might be able to just change on the syntax end?
Cheers!

**Comment by mwarger** [comment]
this was closed with https://github.com/esbenp/react-native-clean-form/pull/10
